name: econ-python-environment
channels:
- conda
- defaults
dependencies:
- alabaster=0.7.10=py35_0
- babel=2.5.0=py35_0
- certifi=2016.2.28=py35_0
- docutils=0.14=py35_0
- imagesize=0.7.1=py35_0
- jinja2=2.9.6=py35_0
- markupsafe=1.0=py35_0
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- pygments=2.2.0=py35_0
- python=3.5.0=1
- pytz=2017.2=py35_0
- readline=6.2=2
- requests=2.14.2=py35_0
- setuptools=36.4.0=py35_1
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.3.5=py35_0
- sphinx_rtd_theme=0.2.4=py35_0
- sphinxcontrib=1.0=py35_0
- sphinxcontrib-websupport=1.0.1=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.11=0
- pip:
  - sphinx-rtd-theme==0.2.4
